# Generated by Django 3.1 on 2020-08-20 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=13)),
                ('telefono', models.CharField(max_length=13)),
                ('correo', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=30)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.ciudad')),
            ],
        ),
    ]
